services:
  - type: web
    name: nomes-planilha
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SHEET_PUBLISH_ID
        value: 2PACX-1vQL2uV2BS5DCGOlUQx4X2A7ABEWgC-c3CYA46B3S92pUG5H8VhFXta7qL00F3XjdqolkZ9jEPIqrp3Q
      - key: SHEET_TAB_NAME
        value: Nomes
